import { Vehicle, AppLocation } from './types';

export const VEHICLES: Vehicle[] = [
  {
    id: 'vehicle-hiace',
    model_name: 'Toyota Hiace Commuter Deluxe',
    type: 'van',
    plate_number: 'TBD-001',
    daily_rate: 4500,
    status: 'available',
    features: ['Coastal: PHP 4,500/day', 'Mountain: PHP 5,000/day', 'With Driver & Gas'],
    badge: 'Best for Groups',
    seats: 14,
    transmission: 'With Driver',
    fuelPolicy: 'Driver and gas included',
    bestFor: 'Port transfers, family groups, and coastal tours',
    requirements: ['Valid ID', 'Reservation deposit', 'Pickup details'],
    images: ['/assets/vehicle/hiace-commuter-deluxe.jpg'],
  },
  {
    id: 'vehicle-tamaraw',
    model_name: 'Toyota Tamaraw Commuter',
    type: 'van',
    plate_number: 'TBD-002',
    daily_rate: 4500,
    status: 'available',
    features: ['Coastal: PHP 4,500/day', 'Mountain: PHP 5,000/day', 'With Driver & Gas'],
    badge: 'Tour Ready',
    seats: 10,
    transmission: 'With Driver',
    fuelPolicy: 'Driver and gas included',
    bestFor: 'Island day tours and resort transfers',
    requirements: ['Valid ID', 'Reservation deposit', 'Pickup details'],
    images: ['/assets/vehicle/tamaraw-commuter.png'],
  },
  {
    id: 'vehicle-vios',
    model_name: 'Toyota Vios',
    type: 'car',
    plate_number: 'TBD-003',
    daily_rate: 2200,
    status: 'available',
    features: ['Self Drive', '5 Seater', 'Sedan'],
    badge: 'Comfort Pick',
    seats: 5,
    transmission: 'Automatic',
    fuelPolicy: 'Fuel returned as received',
    bestFor: 'Couples, small families, and rainy-day island drives',
    requirements: ['Valid driver license', 'Valid ID', 'Security deposit'],
    images: ['/assets/vehicle/toyota-vios.png'],
  },
  {
    id: 'vehicle-spresso',
    model_name: 'Suzuki S-Presso',
    type: 'car',
    plate_number: 'TBD-004',
    daily_rate: 2000,
    status: 'available',
    features: ['Self Drive (Manual)', 'Compact', 'Fuel Efficient'],
    badge: 'Budget Car',
    seats: 5,
    transmission: 'Manual',
    fuelPolicy: 'Fuel returned as received',
    bestFor: 'Budget-friendly self-drive trips around Siquijor',
    requirements: ['Valid driver license', 'Valid ID', 'Security deposit'],
    images: ['/assets/vehicle/suzuki-spresso.png'],
  },
  {
    id: 'vehicle-avanza',
    model_name: 'Toyota Avanza',
    type: 'car',
    plate_number: 'TBD-005',
    daily_rate: 2700,
    status: 'available',
    features: ['Self Drive', '7 Seater', 'MPV'],
    badge: 'Family Choice',
    seats: 7,
    transmission: 'Automatic',
    fuelPolicy: 'Fuel returned as received',
    bestFor: 'Families and groups with luggage',
    requirements: ['Valid driver license', 'Valid ID', 'Security deposit'],
    images: ['/assets/vehicle/toyota-avanza.png'],
  },
  {
    id: 'vehicle-tuktuk',
    model_name: 'Bajaj Tuktuk',
    type: 'tuktuk',
    plate_number: 'TBD-006',
    daily_rate: 1300,
    status: 'available',
    features: ['Self Drive (Manual)', 'Island Vibes', '3 Seater'],
    badge: 'Island Vibes',
    seats: 3,
    transmission: 'Manual',
    fuelPolicy: 'Fuel returned as received',
    bestFor: 'Short beach hops and relaxed island cruising',
    requirements: ['Valid driver license', 'Valid ID', 'Security deposit'],
    images: ['/assets/vehicle/tuktuk.png'],
  },
  {
    id: 'vehicle-beat',
    model_name: 'Honda Beat 110cc',
    type: 'motorbike',
    plate_number: 'TBD-007',
    daily_rate: 350,
    status: 'available',
    features: ['No gas inclusion', 'Automatic', 'Two Helmets'],
    badge: 'Budget Scooter',
    seats: 2,
    transmission: 'Automatic',
    fuelPolicy: 'Fuel not included',
    bestFor: 'Solo travelers and budget island loops',
    requirements: ['Valid driver license', 'Valid ID', 'Helmet use required'],
    images: ['/assets/vehicle/honda-beat-110cc.png'],
  },
  {
    id: 'vehicle-fazzio',
    model_name: 'Yamaha Fazzio 125cc',
    type: 'motorbike',
    plate_number: 'TBD-008',
    daily_rate: 550,
    status: 'available',
    features: ['No gas inclusion', 'Classic Style', 'Two Helmets'],
    badge: 'Stylish Ride',
    seats: 2,
    transmission: 'Automatic',
    fuelPolicy: 'Fuel not included',
    bestFor: 'Couples, cafe stops, and scenic coastal roads',
    requirements: ['Valid driver license', 'Valid ID', 'Helmet use required'],
    images: ['/assets/vehicle/yamaha-fazzio-125cc.png'],
  },
  {
    id: 'vehicle-crf',
    model_name: 'Honda CRF 150L',
    type: 'motorbike',
    plate_number: 'TBD-009',
    daily_rate: 700,
    status: 'available',
    features: ['No gas inclusion', 'Dirt Bike', 'Two Helmets'],
    badge: 'Adventure Pick',
    seats: 2,
    transmission: 'Manual',
    fuelPolicy: 'Fuel not included',
    bestFor: 'Confident riders and mountain roads',
    requirements: ['Valid driver license', 'Valid ID', 'Helmet use required'],
    images: ['/assets/vehicle/honda-crf-150l.png'],
  },
];

export const LOCATIONS: AppLocation[] = [
  { id: 'loc-1', name: 'Siquijor Port', type: 'Port', deliveryFee: 0 },
  { id: 'loc-2', name: 'Larena Port', type: 'Port', deliveryFee: 200 },
  { id: 'loc-3', name: 'San Juan Beach Area', type: 'Resort', deliveryFee: 300 },
  { id: 'loc-4', name: 'Paliton Beach', type: 'Resort', deliveryFee: 350 },
  { id: 'loc-5', name: 'Habibi & Shaun Rentals HQ', type: 'Office', deliveryFee: 0 },
];
